# Generated by Django 2.2 on 2019-06-12 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bukutamu', '0012_auto_20190612_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='pelaporan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelanggaran', models.CharField(max_length=100)),
                ('tempat', models.CharField(max_length=100)),
                ('tanggal', models.DateTimeField()),
                ('tamu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bukutamu.Tamu')),
            ],
        ),
    ]
