# Generated by Django 2.2 on 2019-06-13 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bukutamu', '0014_auto_20190612_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='pelaporan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelapor', models.CharField(max_length=100)),
                ('uid_pelapor', models.CharField(max_length=100)),
                ('tid_pelapor', models.CharField(max_length=100)),
                ('tanggal_pelanggaran', models.DateTimeField()),
                ('tanggal_pelaporan', models.DateTimeField()),
                ('tipe_aktivitas_12', models.CharField(max_length=100)),
                ('sub_kategori', models.CharField(max_length=100)),
                ('positif', models.BooleanField()),
                ('action_plan1', models.CharField(max_length=100)),
                ('action_plan2', models.CharField(max_length=100)),
                ('pelaku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bukutamu.Tamu')),
            ],
        ),
    ]
