# Generated by Django 2.2 on 2019-04-14 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tamu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tamu', models.CharField(max_length=100)),
                ('perusahaan', models.CharField(max_length=100)),
                ('daerah_perusahaan', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Kedatangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_kedatangan', models.DateTimeField(verbose_name='datang')),
                ('alasan_kedatangan', models.CharField(max_length=300)),
                ('tanggal_keluar', models.DateTimeField(verbose_name='keluar')),
                ('lama_kedatangan', models.DateTimeField(verbose_name='lama')),
                ('tamu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bukutamu.Tamu')),
            ],
        ),
    ]
