# Generated by Django 2.2.2 on 2019-06-18 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_departemen', models.CharField(max_length=50)),
                ('penanggungjawab', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tamu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='000000000000', max_length=12)),
                ('tipeid', models.CharField(max_length=20)),
                ('nama_tamu', models.CharField(max_length=100)),
                ('no_hp_tamu', models.CharField(max_length=30)),
                ('jenis_kelamin', models.CharField(max_length=20)),
                ('signed_in', models.BooleanField()),
                ('perusahaan', models.CharField(max_length=100)),
                ('terakhir_datang', models.DateTimeField(verbose_name='terakhir_datang')),
                ('image', models.ImageField(null=True, upload_to='camera/')),
            ],
        ),
        migrations.CreateModel(
            name='Kedatangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_kedatangan', models.DateTimeField(verbose_name='datang')),
                ('bertemu_dengan', models.CharField(max_length=100)),
                ('alasan_kedatangan', models.CharField(max_length=300)),
                ('tanggal_keluar', models.DateTimeField(verbose_name='keluar')),
                ('lama_kedatangan', models.DurationField(verbose_name='lama')),
                ('suhu_badan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('terdapat_luka_terbuka', models.BooleanField()),
                ('sakit', models.CharField(max_length=100, null=True)),
                ('out', models.BooleanField()),
                ('departemen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bukutamu.Departemen')),
                ('tamu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bukutamu.Tamu')),
            ],
        ),
    ]
