# Generated by Django 2.2.2 on 2019-06-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukutamu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamu',
            name='saved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tamu',
            name='jenis_kelamin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tamu',
            name='nama_tamu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tamu',
            name='no_hp_tamu',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tamu',
            name='perusahaan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tamu',
            name='signed_in',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tamu',
            name='terakhir_datang',
            field=models.DateTimeField(null=True, verbose_name='terakhir_datang'),
        ),
    ]
