# Generated by Django 2.2 on 2019-04-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukutamu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamu',
            name='uid',
            field=models.CharField(default='000000000000', max_length=12),
        ),
    ]
