# Generated by Django 2.2 on 2019-04-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukutamu', '0002_tamu_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='kedatangan',
            name='bertemu_dengan',
            field=models.CharField(default='budi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamu',
            name='jenis_kelamin',
            field=models.CharField(default='apache', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamu',
            name='no_hp_tamu',
            field=models.CharField(default='000', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamu',
            name='suhu_badan',
            field=models.DecimalField(decimal_places=2, default=34.3, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamu',
            name='terdapat_luka_terbuka',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamu',
            name='tipeid',
            field=models.CharField(default='ktp', max_length=20),
            preserve_default=False,
        ),
    ]
