# Generated by Django 2.2 on 2019-04-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukutamu', '0003_auto_20190414_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamu',
            name='suhu_badan',
        ),
        migrations.RemoveField(
            model_name='tamu',
            name='terdapat_luka_terbuka',
        ),
        migrations.AddField(
            model_name='kedatangan',
            name='suhu_badan',
            field=models.DecimalField(decimal_places=2, default=34.32, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kedatangan',
            name='terdapat_luka_terbuka',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
