# Generated by Django 2.2 on 2019-04-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukutamu', '0005_tamu_terakhir_datang'),
    ]

    operations = [
        migrations.AddField(
            model_name='kedatangan',
            name='signedout',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
