# Generated by Django 2.2 on 2019-04-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukutamu', '0007_auto_20190414_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kedatangan',
            name='lama_kedatangan',
            field=models.DurationField(verbose_name='lama'),
        ),
    ]
