# Generated by Django 2.2 on 2019-04-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukutamu', '0008_auto_20190414_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamu',
            name='signed_in',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
