# Generated by Django 2.2 on 2019-05-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukutamu', '0009_tamu_signed_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamu',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
