# Generated by Django 2.2 on 2019-05-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukutamu', '0010_tamu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kedatangan',
            name='sakit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tamu',
            name='image',
            field=models.ImageField(null=True, upload_to='bukutamu/static/bukutamu/camera/'),
        ),
    ]
