# Generated by Django 2.2 on 2019-06-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukutamu', '0011_auto_20190501_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamu',
            name='daerah_perusahaan',
        ),
        migrations.AlterField(
            model_name='tamu',
            name='image',
            field=models.ImageField(null=True, upload_to='static/bukutamu/camera/'),
        ),
    ]
