# Generated by Django 2.2 on 2019-06-18 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bukutamu', '0014_auto_20190612_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_departemen', models.CharField(max_length=50)),
                ('penanggungjawab', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tamu',
            name='image',
            field=models.ImageField(null=True, upload_to='camera/'),
        ),
        migrations.AddField(
            model_name='kedatangan',
            name='departemen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bukutamu.Departemen'),
        ),
    ]
